### ISSUE TITLE
Doesn't work with d3 elements

### ISSUE THREAD

**Issue by mrsiva26** [asatour/jquery-domPath#4]
I have a d3 svg element that conatins some circles inside it and whenever I am trying to get domPath of such d3 elements, there is "TypeError: el.className.trim is not a function" error in console from
jquery.domPath.js:49
elClass = '.' + el.className.trim().replace(/ /g, '.');

Error log from console:
jquery.domPath.js:49 Uncaught TypeError: el.className.trim is not a
 functiongetDomPath @ jquery.domPath.js:49
(anonymous function) @ jquery.domPath.js:72
m.extend.each @ jquery.js:384
m.fn.m.each @ jquery.js:136
jQuery.fn.extend.domPath @ jquery.domPath.js:64
(anonymous function) @ myfile.php:132
m.event.dispatch @ jquery.js:4670
r.handle @ jquery.js:4338

**Comment by asatour** [comment]
Hi, Could you send me some lines of the code you are using? maybe you are not using a jquery element and you should wrappe it inside $()

**Comment by asatour** [comment]
Couldn't reproduce this bug with d3 elements
